spring:
  datasource:
    url: jdbc:postgresql://auth-db-postgres:5432/auth-micro-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true