spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-micro-db
    username: postgres
    password: 267115
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true