spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_INTERNAL_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:session-schema.sql

  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: auth

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - debug
          - env

grpc:
  client:
    email-validator-service:
      address: static://networking-service:${GRPC_PORT}
      negotiation-type: plaintext
    account-creation-service:
      address: static://networking-service:${GRPC_PORT}
      negotiation-type: plaintext
    role-resolver-service:
      address: static://networking-service:${GRPC_PORT}
      negotiation-type: plaintext

server:
  port: ${HTTP_PORT}

jwt:
  secret: ${JWT_SECRET}