spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
#    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_INTERNAL_PORT}/${POSTGRES_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}

#    url: jdbc:postgresql://localhost:5432/auth-micro-db
#    username: postgres
#    password: 267115

  sql:
    init:
      mode: always
      schema-locations: classpath:session-schema.sql

  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - debug
          - env

jwt_secret: ${JWT_SECRET}